#!/usr/local/cpanel/3rdparty/bin/perl

# --------------------------------------------------------
#  cPanel AWS
#  georgebohnisch.com
#
#  This script outputs XML data passed from hook execution
#
#  A file is created (/tmp/cpanel_hook_output) containing
#  the XML output structure.
#
#  File: debug_hook
#  Version: 1.0
# --------------------------------------------------------

use strict;
use warnings;

use XML::Simple;
use Data::Dumper;

my $xml;

while (<STDIN>) {
        $xml .= $_;
}

open(my $fh, ">>", "/tmp/cpanel_hook_output");
print {$fh} "\tXML:\n$xml\n";
close($fh);
